version: '3.7'

services:
  lxc-platform-webui:
    image: lxc-platform-webui:latest
    networks:
    - lxc-frontend
    container_name: lxc-platform-webui
    volumes:
    - ./src:/usr/app/src
    environment:
    - NODE_ENV=development
    - REACT_APP_API_URL=http://localhost:8081
    - REACT_APP_LOCALE=false
    - PORT=3003
    ports:
    - '3003:3003'

networks:
  lxc-frontend: